# permissions for end users to edit emitters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: emitter-editor-role
rules:
- apiGroups:
  - webapp.hello.operator.com
  resources:
  - emitters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.hello.operator.com
  resources:
  - emitters/status
  verbs:
  - get
